# 0. 라이브러리 설정

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. 데이터 설정

In [47]:
x_train = np.array([[2,3,1],[4,8,9],[6,2,7],[8,4,6]])

In [48]:
y_train = np.array([[3],[7],[5],[8]])

In [49]:
n_samples = x_train.shape[0]

In [50]:
n_features = x_train.shape[1]

# 2. 가설함수 정의

In [51]:
W = np.ones((3,1))

In [52]:
b = np.ones((1,1))

In [53]:
def f(X):
    return np.matmul(X, W) + b

In [54]:
y_pred = f(x_train)

# 3. cost 함수 정의

In [55]:
def loss_function(y_pred, y_train):
    n_samples = y_train.shape[0]
    deviation = y_pred - y_train
    deviation_squared = deviation**2
    loss = (1 / n_samples) * np.sum(deviation_squared)

    return loss

In [56]:
loss_function(y_pred, y_train)

120.75

In [57]:
def gradient(x_train, y_train, y_pred):
    n_samples = y_train.shape[0]
    dw = (1 / n_samples) * np.matmul(x_train.transpose(), (y_pred - y_train))
    db = (1/n_samples) * np.sum(y_pred - y_train, axis=0, keepdims=True)

    return dw, db

In [58]:
def gradient_descent(W, b, learning_rate, dw, db):
    W = W - learning_rate * dw
    b = b - learning_rate * db
    
    return W, b

In [59]:
dw, db = gradient(x_train, y_train, y_pred)

In [60]:
gradient_descent(W, b, 0.01, dw, db)

(array([[0.445],
        [0.505],
        [0.295]]), array([[0.8975]]))

In [61]:
losses = []
for num_iter in range(100):
    y_pred = f(x_train)
    loss = loss_function(y_pred, y_train)
    losses.append(loss)

    dw, db = gradient(x_train, y_train, y_pred)
    W, b = gradient_descent(W, b, 0.01, dw, db)

    print(W)
    print(loss)

[[0.445]
 [0.505]
 [0.295]]
120.75
[[0.3887    ]
 [0.44238125]
 [0.20766875]]
2.186206250000003
[[0.39068034]
 [0.43105031]
 [0.19320272]]
0.5116925067382809
[[0.39909509]
 [0.42609955]
 [0.18743155]]
0.46162967009817335
[[0.40786214]
 [0.42221797]
 [0.18279302]]
0.4367769587552104
[[0.41628796]
 [0.4187595 ]
 [0.17839231]]
0.4146555905515002
[[0.42431231]
 [0.41562874]
 [0.17412009]]
0.3946924827483572
[[0.43194831]
 [0.41279632]
 [0.16995972]]
0.37664805920621675
[[0.43921655]
 [0.41024177]
 [0.16590566]]
0.3603136112810823
[[0.44613736]
 [0.4079467 ]
 [0.16195388]]
0.3455040924409891
[[0.45273002]
 [0.40589392]
 [0.15810065]]
0.33205535688494403
[[0.45901271]
 [0.40406732]
 [0.15434246]]
0.3198217658500536
[[0.46500252]
 [0.40245178]
 [0.15067597]]
0.3086740698280373
[[0.4707156 ]
 [0.40103311]
 [0.14709799]]
0.29849753424205605
[[0.47616711]
 [0.39979797]
 [0.14360547]]
0.28919028054820534
[[0.48137138]
 [0.39873386]
 [0.14019553]]
0.28066181796409595
[[0.48634188]
 [0.39782906]
 [